# Generated by Django 3.0.5 on 2022-10-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_product_games_product_laptop_product_parts_product_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_parts',
            new_name='Product_game',
        ),
        migrations.RenameModel(
            old_name='Product_games',
            new_name='Product_part',
        ),
    ]
